# 固有値分解


numpy.matrix
https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

numpy.diag
https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html

numpy.linalg.eig
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html

In [1]:
import numpy as np

print(np.__version__)

1.16.2


In [4]:
A = np.matrix([[2,3,5,7],
               [11,13,17,19],
               [23,29,31,37],
               [41,43,47,53]])

print(A)

[[ 2  3  5  7]
 [11 13 17 19]
 [23 29 31 37]
 [41 43 47 53]]


In [11]:
from numpy import linalg as LA

In [13]:
w, v = LA.eig(A)

print(w)
print(v)

[104.33603014  -4.54479131   1.02294627  -1.8141851 ]
[[ 0.08851383  0.5100893   0.43683788  0.179836  ]
 [ 0.27543406  0.27501112 -0.43784015 -0.40940659]
 [ 0.5366094   0.25224171 -0.57398719  0.76267732]
 [ 0.79268641 -0.77495284  0.53666319 -0.46729923]]


In [23]:
V = np.matrix(v)
W = np.diag(w)

print('V * diag(w):\n{}'.format(V*W))

V * diag(w):
[[ 9.23518165 -2.31824941  0.44686168 -0.32625579]
 [28.73769633 -1.24986815 -0.44788694  0.74273934]
 [55.98769408 -1.14638593 -0.58715806 -1.38363782]
 [82.70575268  3.52199896  0.54897761  0.84776729]]


In [21]:
print('A * V:\n{}'.format(A*V))

A * V:
[[ 9.23518165 -2.31824941  0.44686168 -0.32625579]
 [28.73769633 -1.24986815 -0.44788694  0.74273934]
 [55.98769408 -1.14638593 -0.58715806 -1.38363782]
 [82.70575268  3.52199896  0.54897761  0.84776729]]


In [24]:
print('diag(w) * V:\n{}'.format(W*V))

diag(w) * V:
[[ 9.23518165 53.2206924  45.57792977 18.76337432]
 [-1.25179032 -1.24986815  1.98989209  1.86066753]
 [ 0.54892258  0.25802971 -0.58715806  0.78017791]
 [-1.43807986  1.4059079  -0.97360636  0.84776729]]


## 参考資料

numpy.matrix
https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

numpy.diag
https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html

numpy.linalg.eig
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html